import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import { connectDB } from "./config/db.js";
import conversationRoutes from "./routes/conversations.js";
import messageRoutes from "./routes/messages.js";
import messageImagesRoute from "./routes/messages-image.js";

dotenv.config();
const app = express();
app.use(cors());
app.use(helmet());
app.use(express.json());
app.use(rateLimit({ windowMs: 10000, max: 50 }));
app.use("/conversations", conversationRoutes);
app.use("/messages", messageRoutes);
connectDB();
app.listen(process.env.PORT || 5000, ()=>console.log("✅ PRYDE backend running"));
app.use("/messages", messageImagesRoute);
